doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
#        server_version: '10.01'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        dbname: '%env(DATABASE_NAME)%'
        host: '%env(DATABASE_HOST)%'
        port: ~
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
