fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

### Main Routes ###
app_main_index:
    path: /
    methods: [GET]
    controller: App\Controller\MainController::index

app_main_order:
    path: /o/{order}
    methods: [GET]
    controller: App\Controller\MainController::order

app_main_heart:
    path: /heart
    methods: [GET]
    controller: App\Controller\MainController::heart

app_main_flower:
    path: /flower
    methods: [GET]
    controller: App\Controller\MainController::flower

app_main_thankyoupage:
    path: thankyoupage
    methods: [GET]
    controller: App\Controller\MainController::thankyoupage

#Сторити замовлення - не для адмінки
app_order_create:
    path: order
    methods: [POST]
    controller: App\Controller\OrderController::create

app_order_create_items:
    path: order/{order}/items
    methods: [POST]
    controller: App\Controller\OrderController::createItems

### ADMIN Routes ###
app_admin_index:
    path: admin
    methods: [GET]
    controller: App\Controller\AdminController::index

#Список замовленнь
app_order_index:
    path: admin/orders
    methods: [GET]
    controller: App\Controller\OrderController::index

#Вибране замовлення
app_order_item_index:
    path: admin/orders/{order}
    methods: [GET]
    controller: App\Controller\OrderItemController::index

#Добавити фото + комент
app_order_item_create:
    path: admin/orders/{order}
    methods: [POST]
    controller: App\Controller\OrderItemController::create

#Активувати (status=true) фото в замовлені або деактивувати (не передавати нічого)
app_order_item_active:
    path: admin/order_item/{orderItem}/active
    methods: [POST]
    controller: App\Controller\OrderItemController::active

#Добавити|Редагувати коммент
app_order_item_comment:
    path: admin/order_item/{orderItem}/comment
    methods: [POST]
    controller: App\Controller\OrderItemController::comment

#Добавити|Редагувати надпис
app_order_item_inscription:
    path: admin/order_item/{orderItem}/inscription
    methods: [POST]
    controller: App\Controller\OrderItemController::inscription

#Завантажити макет
app_order_item_upload_model:
    path: admin/order_item/{orderItem}/upload/model
    methods: [POST]
    controller: App\Controller\OrderItemController::uploadModel

#Завантажити PSD
app_order_item_upload_psd:
    path: admin/order_item/{orderItem}/upload/psd
    methods: [POST]
    controller: App\Controller\OrderItemController::uploadPsd

#Зробити дубль фото
app_order_item_duplicate:
    path: admin/order_item/{orderItem}/duplicate
    methods: [POST]
    controller: App\Controller\OrderItemController::duplicate

#Зробити дубль фото
app_order_item_download_print:
    path: admin/order_item/{orderItem}/download/print
    methods: [GET]
    controller: App\Controller\OrderItemController::downloadPrint

#Зробити дубль фото
app_activity_index:
    path: admin/activity/{orderItem}
    methods: [GET]
    controller: App\Controller\ActivityController::index
